# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('image_description', models.CharField(default='', max_length=254)),
                ('github_link', models.CharField(blank=True, default='', max_length=254)),
                ('live_link', models.CharField(blank=True, default='', max_length=254)),
            ],
        ),
    ]
