# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-24 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='order_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
