# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-01 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projects_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTechnologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(blank=True, default='', max_length=254)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_technologies', to='home.Projects')),
            ],
        ),
    ]
